_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (44990, 44995)
  MAX_ITER: 45000
  IMG_PER_BATCH_LABEL: 32
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("voc_2012_trainval",)
  TRAIN_LABEL: ("voc_2007_trainval",)
  TRAIN_UNLABEL: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
SEMISUPNET:
  Trainer: "mum"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  TYPE: "mix_unmix"
  NT: 4
  NG: 4
  TILE_PROP: 1.
  SUPTILE: False
  INIT_MOMENTUM: False
  DYNAMIC_EMA: 30000
TEST:
  EVAL_PERIOD: 3000
  EVALUATOR: "COCOEval"
OUTPUT_DIR: "logs/voc"
